version: '3.9'

services:

  mongo_db:
    image: mongo:latest
    restart: always
    ports:
      - "2717:27017"
    volumes:
      - mongo-db:/data/db 
  api-nodejs:
    image: pranavdazzler007/api:latest
    ports:
      - 3000:3000
    environment:
      PORT: 3000
      MONGODB_URI: mongodb://mongo_db:27017
      DB_NAME: my_db
      NAME: pranav
    depends_on:  
      - mongo_db 
volumes:
  mongo_db: {}

      